version: 1
services:
  - type: web
    name: task-manager-backend
    env: python
    region: oregon
    plan: free
    branch: main
    rootDir: backend
    buildCommand: pip install -r ../requirements.txt
    startCommand: uvicorn src.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: JWT_SECRET_KEY
        value: umemasultan2026taskmanager
      - key: PYTHON_VERSION
        value: 3.11.0
